// let products = [
//     {
//         id: 1001,
//         title: "Dance Class",
//         Fees: 200.00,
//         image: "./images/dancing.png",
//         location: "Abu dhabi",
//         availableInventory: 5,
//     },
//     {
//         id: 1002,
//         title: "Yoga Class",
//         Fees: 250.00,
//         image: "./images/yoga.png",
//         location: "Dubai",
//         availableInventory: 5,
//     },
//     {
//         id: 1003,
//         title: "Gardening Class",
//         Fees: 300.00,
//         image: "./images/gardening.png",
//         location: "Sharjah",
//         availableInventory: 5,
//     },
//     {
//         id: 1004,
//         title: "Martial Arts Class",
//         Fees: 350.00,
//         image: "./images/martialArts.png",
//         location: "Fujairah",
//         availableInventory: 5,
//     },
//     {
//         id: 1005,
//         title: "Astronomy Class",
//         Fees: 500.00,
//         image: "./images/astronomy.png",
//         location: "Al Ain",
//         availableInventory: 5,
//     },
//     {
//         id: 1006,
//         title: "Board Game Class",
//         Fees: 100.00,
//         image: "./images/boardGame.png",
//         location: "Dubai",
//         availableInventory: 5,
//     },
//     {
//         id: 1007,
//         title: "Cooking Class",
//         Fees: 300.00,
//         image: "./images/cooking.png",
//         location: "Abu dhabi",
//         availableInventory: 5,
//     },
//     {
//         id: 1008,
//         title: "Photography Class",
//         Fees: 450.00,
//         image: "./images/photography.png",
//         location: "Ajman",
//         availableInventory: 5,
//     },
//     {
//         id: 1009,
//         title: "Art and Craft Class",
//         Fees: 400.00,
//         image: "./images/artAndCraft.png",
//         location: "Sharjah",
//         availableInventory: 5,
//     },
//     {
//         id: 1010,
//         title: "Coding/Programming Class",
//         Fees: 550.00,
//         image: "./images/coding.png",
//         location: "Dubai",
//         availableInventory: 5,
//     },
// ]

